app/controllers/api/v1/testimonials_controller.rb
app/models/testimonial.rb
config/routes.rb
db/migrate/20220317235629_create_testimonials.rb
db/migrate/20220318120544_add_discarded_at_to_testimonials.rb
db/schema.rb
spec/factories/testimonials.rb
spec/models/testimonial_spec.rb
spec/requests/api/v1/testimonials_spec.rb

Crear modelo, migración y controlador base de Testimonials:
Campos:
name: VARCHAR NOT NULL
content: VARCHAR NULLABLE
timestamps y softDeletes
El modelo puede o no tener una imagen, y se debera utilizar Active Storage
Agregado estructuras bases de acuerdo a las especificaciones, . Instaladas gemas Discard y Active Storage

feat-0T170-20-create-migration-and-controller-base-of-testimonials

---

app/controllers/api/v1/organizations_controller.rb
app/models/organization.rb
db/migrate/20220319150610_create_organizations.rb
db/migrate/20220319150654_add_discarded_at_to_organizations.rb
db/schema.rb
spec/factories/organizations.rb
spec/models/organization_spec.rb
spec/requests/api/v1/organizations_spec.rb

Campos:
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
address: VARCHAR NULLABLE
phone: INTEGER NULLABLE
email: VARCHAR NOT NULL
welcomeText: TEXT NOT NULL
aboutUsText: TEXT NULLABLE
timestamps y softDeletes
El modelo debe tener una imagen, y se debera utilizar Active Storage

feat-OT170-15-create-migration-and-base-controller-of-organization

---

app/controllers/api/v1/testimonials_controller.rb
app/models/testimonial.rb

This push , have a correction from testimonials_controller and a testimonial.rb

fixticketTestimonialsfeat0T170-20

---

Gemfile
Gemfile.lock
app/controllers/api/v1/auth/registrations_controller.rb
app/controllers/application_controller.rb
app/controllers/concerns/authenticate_request.rb
app/controllers/concerns/create_session.rb
app/models/user.rb
app/serializers/user_serializer.rb
config/routes.rb
lib/json_web_token.rb

COMO usuario
QUIERO registrarme en el sistema
PARA ser parte del mismo
- Se debe hacer una petición POST /auth/register 
- El endpoint deberá validar los campos Nombre, Apellido, Email, Contraseña. 
- La contraseña debe ser encriptada. 
- Deberá devolver como respuesta el usuario generado.
- Validar
- Encriptar contraseña
- Almacenar en base de datos
Para esto utilizaremos Ruby JWT, sin ninguna GEMA adicional https://github.com/jwt/ruby-jwt[]

feat OT170-23: register

---

app/controllers/api/v1/organizations_controller.rb
app/models/session.rb
app/serializers/organization_serializer.rb
app/serializers/user_serializer.rb
config/routes.rb
db/schema.rb
spec/factories/sessions.rb
spec/models/session_spec.rb

COMO usuario
QUIERO ver los datos de una Organización
PARA tener conocimiento sobre ella.
Criterios de aceptación: 
Se debe realizar una petición GET hacia ruta /organization/public
El endpoint debe devolver solamente los campos name, image, phone y address de la Organización

feat-OT170-22-endpoint-public-data-of-the-organization

---

app/controllers/api/v1/users_controller.rb
app/models/session.rb
config/routes.rb
db/schema.rb
spec/factories/sessions.rb
spec/models/session_spec.rb

COMO usuario
QUIERO eliminar mi usuario
PARA darme de baja del sistema
DELETE a /user/:id Deberá reicibir el id del usuario con el método DELETE. El borrado debe ser lógico.

feat OT-170-32: endpoint delete user

---

app/controllers/api/v1/slides_controller.rb
app/models/organization.rb
app/models/session.rb
app/serializers/slide_serializer.rb
config/environments/development.rb
config/routes.rb
db/schema.rb
spec/factories/sessions.rb
spec/models/session_spec.rb

QUIERO ver el listados de Slides
PARA ver el contenido de forma gráfica.
Se debe hacer una petición GET a /Slides. 
Devolverá el listado de Slides, con la miniatura y el orden del mismo

feat-0T170-56-endpoint-list-of-slides

---

Gemfile.lock
app/controllers/api/v1/categories_controller.rb
app/models/organization.rb
app/models/session.rb
app/serializers/category_serializer.rb
app/serializers/organization_serializer.rb
config/routes.rb
db/migrate/20220330041826_add_missing_reference.rb
db/schema.rb
spec/factories/categories.rb
spec/factories/organizations.rb
spec/factories/sessions.rb
spec/models/category_spec.rb
spec/models/organization_spec.rb
spec/models/session_spec.rb

QUIERO modificar una categoría existente
PARA mantener la información actualizada
PUT /categories/:id - Deberá validar que la categoría existe y actualizarla, caso contrario devolver un error

feat/OT170-43: endpoint actualizacion categorias

---

app/controllers/api/v1/categories_controller.rb
app/serializers/category_serializer.rb
config/routes.rb
db/schema.rb

QUIERO listar las Categorías
PARA poder gestionar las Categorías
GET a /categories. Devolverá el listado de categories. Solamente devolverá el campo name de las mismas

feat-OT170-40-endpoint-list-of-categories

---

app/controllers/api/v1/news_controller.rb
app/models/session.rb
app/serializers/category_serializer.rb
app/serializers/new_serializer.rb
config/routes.rb
db/schema.rb
spec/factories/sessions.rb
spec/models/session_spec.rb

QUIERO actualizar una novedad existente
PARA poder mantener a información actualizada
PUT /news/:id - Deberá validar que la novedad exista en base al id enviado por parámetro. En el caso de que no exista devolver un error, caso contrario actualizar la novedad y devolver la misma con los datos actualizados

feat-OT170-47-endpoint-for-updating-news

---

app/models/activity.rb
app/models/session.rb
db/migrate/20220404203015_create_activities.rb
db/migrate/20220404205905_add_discarded_at_to_activities.rb
db/schema.rb
spec/factories/activities.rb
spec/factories/sessions.rb
spec/models/activity_spec.rb
spec/models/session_spec.rb

Crear migración y modelo de Actividades
Descripción
QUIERO gestionar las Actividades de la ONG
PARA poder informarlas en el sistema
Las Actividades de la ONG podrán ser gestionadas desde el backoffice. Nombre de tabla: activities. Contendrá los campos name, image, content, deletedAt (utilizada para soft delete)

feat-0T70-48-create-migration-and-model-of-activities

---

app/serializers/category_serializer.rb

Fixed repeated line of category serializer

fixed-repeated-line-category-serializer

---

app/controllers/api/v1/organizations_controller.rb

Fixed a wrong letter in a line.

fixed line on organization controller

---

app/controllers/api/v1/news_controller.rb
config/routes.rb

QUIERO ver los detalles de una novedad
PARA poder informar actualizaciones del contenido
GET a /news/:id . Mostrará todos los campos de una entry en base al id enviado por parámetro.

feat/OT170-45: endpoint detalle novedad

---

app/controllers/api/v1/activities_controller.rb
app/models/news.rb
app/models/session.rb
app/serializers/activity_serializer.rb
app/serializers/news_serializer.rb
config/routes.rb
db/schema.rb
spec/factories/news.rb
spec/factories/sessions.rb
spec/models/news_spec.rb
spec/models/session_spec.rb
spec/requests/api/v1/activities_spec.rb

Endpoint Creación Actividades
Descripción
QUIERO dar de alta Actividades
PARA informarlas en el sistema
POST /activities - Deberá validar la existencia de los campos name y content enviados, para almacenar el registro en la tabla activities.

feat-0T170-51-endpoint-creation-activities

---

app/controllers/api/v1/activities_controller.rb
config/routes.rb
db/migrate/20220405124942_create_activities.rb
db/migrate/20220405124952_add_discarded_at_to_activities.rb

Endpoint Actualización Actividades
QUIERO actualizar una actividad existente
PARA mantener la información actualizada
PUT /activities/:id - Deberá validar que la actividad exista en base al id enviado por parámetro. En el caso de que no exista devolver un error, caso contrario actualizarla y devolverla con los datos actualizados

feat-0T170-52-endpoint-update-ativities

---

app/controllers/api/v1/slides_controller.rb
app/models/slide.rb
app/serializers/slide_serializer.rb
config/routes.rb
db/migrate/20220406194518_add_discarded_at_to_slides.rb
db/schema.rb
spec/factories/slides.rb
spec/models/slide_spec.rb

Endpoint Eliminación Slides
QUIERO poder eliminar Slides 
PARA tener la información actualizada al comienzo de la página
Se debe hacer una petición DELETE /Slides/:id 
Deberá validar que el slide existe y eliminarlo, caso contrario devolver un error

feat-0T170-60-endpoint-delete-slides

---

app/models/contact.rb
db/migrate/20220409004626_create_contacts.rb
db/migrate/20220409004809_add_discarded_at_to_contacts.rb
db/schema.rb
spec/factories/contacts.rb
spec/models/contact_spec.rb

QUIERO almacenar los datos enviados al completar un Formulario de Contacto
PARA tener un seguimiento de los mismos
Al completar el Formulario de Contacto, se almacenará en la base de datos. Nombre de tabla: contacts. Contendrá los campos name, phone, email, message, deletedAt (utilizada para soft delete)

feat-OT170-54-create-migration-and-contacts-model

---

app/controllers/api/v1/contacts_controller.rb
app/models/contact.rb
app/serializers/contact_serializer.rb
config/routes.rb
db/migrate/20220409004626_create_contacts.rb
spec/models/contact_spec.rb
spec/requests/api/v1/contacts_spec.rb

Descripción
COMO usuario
QUIERO dar de alta contactos
PARA que estén en la base de datos
Se debe hacer una petición POST /contacts 
-Se verificará que la petición contenga los campos name y email

feat-OT170-55-end-point-almacenar-contactos

---

app/controllers/api/v1/slides_controller.rb
config/routes.rb

- slides' params fixed
- slides' routes fixed

fixed-routes-for-slides

---

app/controllers/api/v1/contacts_controller.rb
config/routes.rb
spec/models/contact_spec.rb

Descripción
COMO usuario
QUIERO listar mis contactos en la página
PARA poder ver todos los que existen
GET /contacts - Devolverá todos los registros de contactos del usuario loggeado.

Feat/OT170-62: end point list contacts

---

app/controllers/api/v1/members_controller.rb
app/models/session.rb
app/serializers/category_serializer.rb
app/serializers/contact_serializer.rb
app/serializers/member_serializer.rb
config/routes.rb
spec/factories/sessions.rb
spec/models/session_spec.rb

70:
Descripción
QUIERO gestionar los Miembros de la ONG
PARA modificar los Miembros de la Organización
Se podrán gestionar los Miembros de la ONG. Nombre de tabla: members. Campos: name, image
71:
Descripción
COMO administrador
QUIERO listar los Miembros
PARA obtener información certera de los Miembros al día.
GET /members - Devolverá todos los Miembros
72:
Descripción
COMO usuario
QUIERO crear un miembro
PARA actualizar la información de la web.
POST /members - Deberá validar que se envíe el campo name, y el mismo sea un string
73:
Descripción
COMO usuario
QUIERO eliminar un miembro
PARA que no sea más parte de la Organización
Criterios de aceptación:DELETE …

feat/OT170-70-71-72-73-74: about members object

---

app/controllers/api/v1/testimonials_controller.rb
app/serializers/testimonial_serializer.rb
config/routes.rb

Added tickets 67 68 69 86 91 of testimonials

Added-all-tickets-of-testimonials

---

app/controllers/api/v1/auth/registrations_controller.rb
app/controllers/api/v1/auth/sessions_controller.rb
app/models/role.rb
app/models/session.rb
app/serializers/role_serializer.rb
app/serializers/user_serializer.rb
config/routes.rb
db/schema.rb
spec/factories/role.rb
spec/factories/sessions.rb
spec/models/session_spec.rb
spec/requests/rol_spec.rb

COMO usuario autenticado
QUIERO obtener un token de autenticación
PARA mantenerme logueado en el sistema
Cuando el usuario se registre en el sitio, deberá loguearse automáticamente Para ello, es necesario modificar el endpoint de registro para que devuelva el token una vez creado el usuario, ya que el mismo se almacenará del lado del cliente

feat/OT170-50: devolver token usuario al registrarse

---

app/controllers/api/v1/auth/users_controller.rb
app/controllers/api/v1/categories_controller.rb
app/controllers/api/v1/comments_controller.rb
config/routes.rb
spec/requests/api/v1/auth/users_spec.rb

COMO usuario
QUIERO obtener mis datos
PARA tener conocimiento de la información que almaceno en el sistema
/GET auth/me - Deben devolver los datos del usuario autenticado, obteniendo al mismo desde el token enviado en el header Authorization

feat/OT170-36: endpoint datos usuario autenticado
